### ISSUE TITLE
Safari 8 NOT Functioning/Broken

### ISSUE THREAD

**Issue by tigz54** [chengyin/WhatFont-Bookmarklet#11]
This plugin no longer works with Safari 8.0.2 (current version) — plugin button appears after install clicking the button no longer does anything.

If you'd like to send me a PM and I'd be happy to test/troubleshoot for you in the case that you do not have access to Safari.

**Comment by chengyin** [comment]
Hey @tigz54, it worked for me in 8.0.3. Do you see any console error log?

After the first installation, you do need to refresh your open tabs
![screen shot 2015-01-10 at 10 58 03 pm](https://cloud.githubusercontent.com/assets/128819/5694561/4422350a-991c-11e4-89bb-d587f2152894.png)
 for the script to load.

**Comment by tigz54** [comment]
Hi  Chengyin,

That totally worked — my bad. thanks a million.


On January 11, 2015 at 1:59:08 PM, Chengyin Liu (notifications@github.com) wrote:

Hey @tigz54, it worked for me in 8.0.3. Do you see any console error log?

After the first installation, you do need to refresh your open tabs

for the script to load.
