### ISSUE TITLE
Retina icon needed

### ISSUE THREAD

**Issue by ggamel** [chengyin/WhatFont-Bookmarklet#12]
Possible to update the icon for extensions to be retina? Looks dated and rough on a rMBp or riMac.

Thanks! :+1:

**Comment by mattmischuk** [comment]
+1

**Comment by ggamel** [comment]
So...no retina icon? Do you need someone to make it?

Will you accept a pull request if a new, retina icon is included?

**Comment by chengyin** [comment]
Hey Greg,

The new retina icon is included in the newest release of the Safari/Chrome extension version.

This repo itself doesn’t contain those assets.

**Comment by ggamel** [comment]
Ahh. My mistake. Thanks for the clarification, @chengyin!


On Wed, Apr 22, 2015 at 5:15 PM, chengyin/WhatFont-Bookmarklet
<reply@reply.github.com>
wrote:
Hey Greg,

The new retina icon is included in the newest release of the Safari/Chrome
extension version.

This repo itself doesn’t contain those assets.


> On Apr 22, 2015, at 3:14 PM, Greg Gamel <notifications@github.com> wrote:
>
> So...no retina icon? Do you need someone to make it?
>
> Will you accept a pull request if a new, retina icon is included?
>
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub
[https://github.com/chengyin/WhatFont-Bookmarklet/issues/12#issuecomment-95354334] .[https://github.com/notifications/beacon/AACHqk9EP6c7OXeXM-tRw-xFfdp7ApBKks5oCBUagaJpZM4DSeda.gif]
