### ISSUE TITLE
Safari Extension Marked as Unsafe by Safari 12

### ISSUE THREAD

**Issue by peirantan** [chengyin/WhatFont-Bookmarklet#24]
After updating my Safari to version 12.0, the browser kicked this extension out citing it’s “unsafe” and “not coming from the Safari Extension Gallery”. Would you mind looking into this?

**Comment by chengyin** [comment]
Thanks for reporting. I will take a look.

**Comment by oblaum** [comment]
i use this extension every day. i hope you'll be managed to bring it to the safari extensions gallery. could be a paid one.

**Comment by chengyin** [comment]
Thanks for all the support! I just released WhatFont for Safari through the Mac App Store. Please give it a try and let me know how it goes!

Download it here: https://itunes.apple.com/us/app/whatfont/id1437138382?mt=12

**Comment by oblaum** [comment]
very very great, chengyin!!! :)

**Comment by curdaneta** [comment]
Thanks **chengyin** !
